### ISSUE TITLE
Package Managers

### ISSUE THREAD

**Issue by moonglum** [moonglum/exogenesis#19]
- [ ] Pathogen? Seems to be a better solution when wrapped. Installer clones pathogen. Then clones all the repos
- [ ] htop-setup (needs to be version aware)
- [ ] iTerm Theme
- [x] Homebrew Tapping incl. [Homebrew Cask](https://github.com/phinze/homebrew-cask) for MacTeX, GUI Software and also awesome things like [Quicklook Plugins](https://github.com/sindresorhus/quick-look-plugins) #50 
- [x] NPM: coffee-script, jslint, jshint #17 
- [ ] Cabal: pandoc
- [ ] OS X Software Updates (`man softwareupdate`)
- [ ] Install standard gems for all rubies: bundler, tmuxinator, guard, gem-man #18
